---
title: "Research"

---
I am a biostatistician trained to develop and apply statistical methodologies across disciplines to generate hypotheses, analyze data, and answer major research questions. My primary research agenda is focused on the development and evaluation of novel methodologies to better analyze, quantify, and visualize public health data across disciplines that are prone to mismeasurement, and translating those methodologies to broad applications. My primary areas of application are air pollution epidemiology, occupational health and safety interventions, and the analysis of infectious disease treatment cohorts. 

### Air Pollution Epidemiology
I am the lead biostatistician on several studies examining the impact of air pollution and neighborhood exposures on health outcomes. We have made several significant contributions to our field, including the first study to report [increased odds of moderate to severe depression](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5332196/) associated with air pollution exposure, and that [mood disorders may mediate](http://www.sciencedirect.com/science/article/pii/S0160412016307589) the effects of air pollution on cognitive impairment. The first study to report significant associations between air pollution and [anemia](http://www.sciencedirect.com/science/article/pii/S0160412016303737). Already we have been able to leverage the size of the [CMS](https://www.cms.gov) database to demonstrate, for the first time, that increased exposure to air pollution was associated with increased risk of respiratory, pneumonia and COPD mortality. [Long-Term PM2.5 Exposure and Respiratory, Cancer, and Cardiovascular Mortality in Older US Adults](https://academic.oup.com/aje/article/186/8/961/3852285)

### Occupational Health and Safety 
I am currently Co-Principal Investigator of an intervention effectiveness project which is part of the [Center for Work, Health and Wellbeing](http://centerforworkhealth.sph.harvard.edu) at the Harvard T.H. Chan School of Public Health, funded as a Center of Excellence by the National Institute for Occupational Safety and Health and its [Total Worker Health®](https://www.cdc.gov/niosh/twh/) Program. Our primary goal is to improve the safety, health, and well-being of construction workers. 
[Our team](http://www.northeastern.edu/ergonomics/) was the first to characterize the [mobility of workers on construction sites](http://onlinelibrary.wiley.com/doi/10.1002/ajim.22461/abstract), and following up on this work I have developed methods to improve both the accuracy and precision of interventions on mobile work forces, by incorporating intervention dose in the modeling, as opposed to performing intent-to-treat or complete case analyses. [The Effect of Workforce Mobility on Intervention Effectiveness Estimates](https://academic.oup.com/annweh/advance-article/doi/10.1093/annweh/wxx112/4830164)

### Other Collaborations
* A better way to handle neutral observations (zeroes) in sign and signed-rank tests: [Link](http://pjsor.com/index.php/pjsor/article/view/2508/742)
* Interesting methods for risk mapping of multidrug-resistant tuberculosis (MDR-TB): [Link](https://www.ncbi.nlm.nih.gov/pubmed/22401962) and  [Link](https://academic.oup.com/jid/article/213/2/287/2459265/Identifying-Hotspots-of-Multidrug-Resistant)
* A permutation test for determining significance in hierarchical clustering [Link](http://www.sciencedirect.com/science/article/pii/S0167947309002217)
* Examining how spatial resolution effects cluster detection: [Link](https://ij-healthgeographics.biomedcentral.com/articles/10.1186/1476-072X-6-52)
* An attempt to classify spatial measurement error in spatial epidemilogy: [Link](https://ij-healthgeographics.biomedcentral.com/articles/10.1186/s12942-016-0049-5)